# R/08_report_tables.R
# Purpose: create Table-1-style comprehensive performance tables (for yourself)
# Inputs: output/results/mc_summary.rds
# Outputs:
#   output/tables/mc_table1_by_scenario_<coef>.tex  (longtable)
#   output/tables/mc_table1_by_scenario_<coef>.csv
#   output/tables/worst_cases_<coef>.csv

suppressPackageStartupMessages({
  library(dplyr)
})

make_dirs <- function() {
  dir.create("output/tables",  recursive = TRUE, showWarnings = FALSE)
  dir.create("output/results", recursive = TRUE, showWarnings = FALSE)
}

pretty_est <- function(x) {
  dplyr::recode(
    x,
    selected_ols  = "Selected OLS",
    zero_impute   = "Zero-impute OLS",
    heckman_2step = "Heckman 2-step",
    .default = x
  )
}

fmt <- function(x, digits = 3) {
  ifelse(is.na(x), "", formatC(x, format = "f", digits = digits))
}

write_table1_longtable <- function(df, tex_path, caption, label) {
  # df columns expected:
  # scenario_id, err_family, n, p_select, rho, estimator,
  # beta_true, mean, bias, sd_emp, rmse, coverage, mean_se, sign_fail
  
  con <- file(tex_path, open = "wt", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  
  cat("% Auto-generated by R/08_report_tables.R\n", file = con)
  cat("\\begin{longtable}{llrrrrrrr}\n", file = con)
  cat(sprintf("\\caption{%s}\\label{%s}\\\\\n", caption, label), file = con)
  cat("\\toprule\n", file = con)
  cat("Estimator & True & Mean & Bias & SD & RMSE & Coverage (\\%) & Mean SE & Sign-fail (\\%)\\\\\n", file = con)
  cat("\\midrule\n", file = con)
  cat("\\endfirsthead\n", file = con)
  
  cat("\\toprule\n", file = con)
  cat("Estimator & True & Mean & Bias & SD & RMSE & Coverage (\\%) & Mean SE & Sign-fail (\\%)\\\\\n", file = con)
  cat("\\midrule\n", file = con)
  cat("\\endhead\n", file = con)
  
  scen_ids <- unique(df$scenario_id)
  
  for (sid in scen_ids) {
    g <- df %>% filter(.data$scenario_id == sid)
    
    meta <- g %>% slice(1)
    
    scen_line <- sprintf(
      "\\multicolumn{9}{l}{\\textbf{Scenario %s:} err=%s, n=%s, p=%s, $\\\\rho$=%s}\\\\\n",
      as.character(meta$scenario_id),
      as.character(meta$err_family),
      as.character(meta$n),
      as.character(meta$p_select),
      as.character(meta$rho)
    )
    
    cat("\\addlinespace[0.5ex]\n", file = con)
    cat(scen_line, file = con)
    cat("\\midrule\n", file = con)
    
    for (i in seq_len(nrow(g))) {
      r <- g[i, ]
      
      cov_pct <- ifelse(is.na(r$coverage), NA_real_, 100 * r$coverage)
      sf_pct  <- ifelse(is.na(r$sign_fail), NA_real_, 100 * r$sign_fail)
      
      line <- paste0(
        r$estimator, " & ",
        fmt(r$beta_true), " & ",
        fmt(r$mean), " & ",
        fmt(r$bias), " & ",
        fmt(r$sd_emp), " & ",
        fmt(r$rmse), " & ",
        fmt(cov_pct, digits = 1), " & ",
        fmt(r$mean_se), " & ",
        fmt(sf_pct, digits = 1),
        " \\\\\n"
      )
      cat(line, file = con)
    }
  }
  
  cat("\\bottomrule\n", file = con)
  cat("\\end{longtable}\n", file = con)
}

make_table1_by_scenario <- function(
    summary_path = "output/results/mc_summary.rds",
    coef_focus   = "x1",
    out_stem     = NULL
) {
  make_dirs()
  
  if (!file.exists(summary_path)) {
    stop("Missing: ", summary_path, " (run run_full_mc.R first)")
  }
  
  tab <- readRDS(summary_path)
  
  df <- tab %>%
    filter(.data$coef_name == coef_focus) %>%
    mutate(estimator = pretty_est(as.character(.data$estimator))) %>%
    select(
      scenario_id, err_family, n, p_select, rho,
      estimator,
      beta_true, mean, bias, sd_emp, rmse, coverage, mean_se, sign_fail
    ) %>%
    arrange(err_family, n, p_select, rho, estimator)
  
  if (is.null(out_stem)) out_stem <- paste0("mc_table1_by_scenario_", coef_focus)
  
  csv_path <- file.path("output/tables", paste0(out_stem, ".csv"))
  write.csv(df, csv_path, row.names = FALSE)
  
  tex_path <- file.path("output/tables", paste0(out_stem, ".tex"))
  write_table1_longtable(
    df       = df,
    tex_path = tex_path,
    caption  = paste0("Monte Carlo performance by scenario (", coef_focus, ")"),
    label    = paste0("tab:mc_perf_", coef_focus)
  )
  
  message("Wrote: ", csv_path)
  message("Wrote: ", tex_path)
  invisible(df)
}

make_worst_case_tables <- function(
    summary_path     = "output/results/mc_summary.rds",
    coef_focus       = "x1",
    focus_estimator  = "heckman_2step",
    top_n            = 10
) {
  make_dirs()
  
  if (!file.exists(summary_path)) {
    stop("Missing: ", summary_path, " (run run_full_mc.R first)")
  }
  
  tab <- readRDS(summary_path) %>%
    filter(.data$coef_name == coef_focus) %>%
    mutate(est_pretty = pretty_est(as.character(.data$estimator)))
  
  df_focus <- tab %>% filter(.data$estimator == focus_estimator)
  
  worst <- df_focus %>%
    transmute(
      scenario_id, err_family, n, p_select, rho,
      estimator = est_pretty,
      beta_true, mean, bias, sd_emp, rmse, coverage, mean_se, sign_fail,
      se_ratio = mean_se / sd_emp
    )
  
  out <- list(
    worst_coverage = worst %>% filter(!is.na(coverage)) %>% arrange(coverage) %>% head(top_n),
    worst_signfail = worst %>% filter(!is.na(sign_fail)) %>% arrange(desc(sign_fail)) %>% head(top_n),
    worst_rmse     = worst %>% arrange(desc(rmse)) %>% head(top_n),
    worst_bias_abs = worst %>% arrange(desc(abs(bias))) %>% head(top_n),
    worst_se_ratio = worst %>% filter(is.finite(se_ratio)) %>% arrange(desc(abs(log(se_ratio)))) %>% head(top_n)
  )
  
  out_path <- file.path("output/tables", paste0("worst_cases_", coef_focus, ".csv"))
  out_df <- bind_rows(lapply(names(out), function(nm) {
    cbind(criterion = nm, out[[nm]])
  }))
  
  write.csv(out_df, out_path, row.names = FALSE)
  message("Wrote: ", out_path)
  
  invisible(out)
}


